### ISSUE TITLE
Create Dapp Store Loader 

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-dapps-store#1]
Need to create dapp store loader - priority status "low"

https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=7%3A1571

**Comment by dariatarakanova** [comment]
Design: https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=2121%3A1231
Animation: https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=2123%3A1323

**Comment by VikMaevskaya** [comment]
@dariatarakanova please make loader format  gif / animated png / svg. one of it.

**Comment by dariatarakanova** [comment]
@VikMaevskaya done and sent to @viktarmikhan yesterday

**Comment by VikMaevskaya** [comment]
@dariatarakanova please, send it to me. Dapp store loader not for him

**Comment by dariatarakanova** [comment]
![dapp store illustration (1) (1)](https://user-images.githubusercontent.com/47353570/181011325-1f3d063e-cb6d-4d85-90b4-87412b139500.svg)
